# Generated by Django 2.2.3 on 2020-08-11 20:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='основной цвет')),
                ('second_color', colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='вторичный цвет')),
                ('logo', models.ImageField(upload_to='static/img/', verbose_name='логотип')),
                ('border_radius', models.IntegerField(max_length=20, verbose_name='закругление')),
                ('phone_number', models.CharField(max_length=256, verbose_name='номер телефона')),
            ],
        ),
    ]
