# Generated by Django 2.2.3 on 2020-08-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SettingApp',
            new_name='SettingsApplication',
        ),
    ]
