# Generated by Django 2.2.3 on 2020-08-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0002_auto_20200811_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsapplication',
            options={'verbose_name': 'Настройка приложения', 'verbose_name_plural': 'Настройки приложения'},
        ),
    ]
