# Generated by Django 2.2.3 on 2020-08-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productimage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фото товара'},
        ),
    ]
