# Generated by Django 2.2.3 on 2020-08-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product',)},
        ),
    ]
