# Generated by Django 2.2.3 on 2020-09-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200827_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='популярное'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=0, max_length=256, verbose_name='цена товара'),
            preserve_default=False,
        ),
    ]
