# Generated by Django 2.2.3 on 2020-09-07 08:15

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200906_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
